### ISSUE TITLE
添加进入HA失败

### ISSUE THREAD

**Issue by zzz929625** [godchenmeng/homeassistant-airpurifierProH#1]
Platform error fan.xiaomi_airpurifierProH - cannot import name 'SERVICE_SET_SPEED' from 'custom_components.xiaomi_airpurifierProH.const' (/config/custom_components/xiaomi_airpurifierProH/const.py)

**Comment by godchenmeng** [comment]
> Platform error fan.xiaomi_airpurifierProH - cannot import name 'SERVICE_SET_SPEED' from 'custom_components.xiaomi_airpurifierProH.const' (/config/custom_components/xiaomi_airpurifierProH/const.py)

please use homeassistant integrations. 
fan:  
 - platform: xiaomi_miio
    host: xxx.xxx.xxx.xxx
    token: xxxx
    model: zhimi.airpurifier.mb3

**Comment by zzz929625** [comment]
> > Platform error fan.xiaomi_airpurifierProH - cannot import name 'SERVICE_SET_SPEED' from 'custom_components.xiaomi_airpurifierProH.const' (/config/custom_components/xiaomi_airpurifierProH/const.py)
> 
> please use homeassistant integrations.
> fan:
> 
> * platform: xiaomi_miio
>   host: xxx.xxx.xxx.xxx
>   token: xxxx
>   model: zhimi.airpurifier.mb3

成功添加进去了但是又没有实体ID添加不进首页很尴尬，去掉model设备就变成不可用

升级最新版后看到Platform error: fan - Requirements for xiaomi_airpurifierProH not found: ['python-miio==0.4.8'].可能是因为库的版本问题？

更改了版本文件然后还是老问题：
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/config.py", line 804, in async_process_component_config
    platform = p_integration.get_platform(domain)
  File "/usr/src/homeassistant/homeassistant/loader.py", line 321, in get_platform
    cache[full_name] = importlib.import_module(
  File "/usr/local/lib/python3.8/importlib/__init__.py", line 127, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 1014, in _gcd_import
  File "<frozen importlib._bootstrap>", line 991, in _find_and_load
  File "<frozen importlib._bootstrap>", line 975, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 671, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 783, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/config/custom_components/xiaomi_airpurifierProH/fan.py", line 13, in <module>
    from .const import (
ImportError: cannot import name 'SERVICE_SET_SPEED' from 'custom_components.xiaomi_airpurifierProH.const' (/config/custom_components/xiaomi_airpurifierProH/const.py)
